name: Bug Report
description: Report a bug or unexpected behavior
title: "[Bug]: "
labels: ["bug"]
body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to report a bug! Please fill out the form below.

  - type: checkboxes
    id: checklist
    attributes:
      label: Checklist
      description: Please confirm the following before submitting
      options:
        - label: I have searched existing issues and this bug hasn't been reported yet
          required: true
        - label: I am using the latest version of SpotiFLAC (Stable Version)
          required: true

  - type: textarea
    id: description
    attributes:
      label: Bug Description
      description: A clear and concise description of what the bug is
      placeholder: Describe the bug...
    validations:
      required: true

  - type: textarea
    id: steps
    attributes:
      label: Steps to Reproduce
      description: Steps to reproduce the behavior
      placeholder: |
        1. Go to '...'
        2. Click on '...'
        3. See error
    validations:
      required: true

  - type: textarea
    id: expected
    attributes:
      label: Expected Behavior
      description: What did you expect to happen?
      placeholder: Describe what you expected...
    validations:
      required: true

  - type: textarea
    id: actual
    attributes:
      label: Actual Behavior
      description: What actually happened?
      placeholder: Describe what actually happened...
    validations:
      required: true

  - type: input
    id: version
    attributes:
      label: App Version
      description: Which version of SpotiFLAC are you using? (Check in Settings > About)
      placeholder: "e.g., v2.2.0"
    validations:
      required: true

  - type: dropdown
    id: platform
    attributes:
      label: Platform
      description: Which platform are you using?
      options:
        - Android
        - iOS
    validations:
      required: true

  - type: input
    id: device
    attributes:
      label: Device & OS Version
      description: What device and OS version are you using?
      placeholder: "e.g., Samsung Galaxy S24, Android 14"
    validations:
      required: true

  - type: dropdown
    id: download-service
    attributes:
      label: Download Service
      description: Which download service were you using when the bug occurred?
      options:
        - Tidal
        - Qobuz
        - Amazon Music
        - Deezer (search only)
        - Not applicable
    validations:
      required: true

  - type: textarea
    id: logs
    attributes:
      label: Logs / Screenshots
      description: |
        If applicable, add logs or screenshots to help explain your problem.
        
        **To get logs:**
        1. Go to Settings > Options > Detailed Logging (turn ON)
        2. Reproduce the bug
        3. Go to Settings > Logs
        4. Tap Share button to export logs
      placeholder: Paste logs or drag & drop screenshots here...

  - type: textarea
    id: additional
    attributes:
      label: Additional Context
      description: Any other context about the problem
      placeholder: Add any other context...
