name: Download Issue
description: Report issues with downloading specific tracks or albums
title: "[Download]: "
labels: ["download-issue"]
body:
  - type: markdown
    attributes:
      value: |
        Having trouble downloading a specific track or album? Please provide details below.

  - type: checkboxes
    id: checklist
    attributes:
      label: Checklist
      description: Please confirm the following before submitting
      options:
        - label: I have tried downloading with a different service (Tidal/Qobuz/Amazon)
          required: true
        - label: I am using the latest version of SpotiFLAC (Stable Version)
          required: true

  - type: dropdown
    id: issue-type
    attributes:
      label: Issue Type
      description: What kind of download issue are you experiencing?
      options:
        - Track not found on service
        - Wrong track downloaded
        - Download fails/errors
        - Metadata incorrect
        - Audio quality issue
        - Other
    validations:
      required: true

  - type: input
    id: spotify-url
    attributes:
      label: Spotify URL
      description: The Spotify URL of the track/album you're trying to download
      placeholder: "https://open.spotify.com/track/..."
    validations:
      required: true

  - type: input
    id: track-info
    attributes:
      label: Track Info
      description: Artist name and track title
      placeholder: "Artist - Track Title"
    validations:
      required: true

  - type: dropdown
    id: download-service
    attributes:
      label: Download Service
      description: Which service did you try to download from?
      options:
        - Tidal
        - Qobuz
        - Amazon Music
        - All services
    validations:
      required: true

  - type: dropdown
    id: search-service
    attributes:
      label: Search Service
      description: Which search service are you using?
      options:
        - Spotify
        - Deezer
    validations:
      required: true

  - type: textarea
    id: description
    attributes:
      label: Description
      description: Describe the issue in detail
      placeholder: |
        What happened? What did you expect?
        If wrong track was downloaded, what track was downloaded instead?
    validations:
      required: true

  - type: input
    id: version
    attributes:
      label: App Version
      description: Which version of SpotiFLAC are you using?
      placeholder: "e.g., v2.2.0"
    validations:
      required: true

  - type: textarea
    id: screenshots
    attributes:
      label: Screenshots / Logs
      description: |
        If applicable, add screenshots or logs.
        
        **To get logs:**
        1. Go to Settings > Options > Detailed Logging (turn ON)
        2. Try downloading the track again
        3. Go to Settings > Logs
        4. Tap Share button to export logs
      placeholder: Drag & drop screenshots or paste logs here...
